// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Analista Financeiro Avançado - Forex & Opções Binárias",
  description: "Análise em tempo real de notícias macroeconômicas para Forex e Opções Binárias. Sinais de trading com alta probabilidade baseados em indicadores econômicos.",
  keywords: "forex, opções binárias, trading, análise técnica, sinais de trading, indicadores econômicos, NFP, FOMC, IPC",
  authors: [{ name: "Analista Financeiro Avançado" }],
  openGraph: {
    title: "Analista Financeiro Avançado - Forex & Opções Binárias",
    description: "Análise em tempo real de notícias macroeconômicas para Forex e Opções Binárias",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
